#!/bin/bash

Func_name=$1
cflow -Tm $Func_name  B2GLoader.cpp > $Func_name.txt
cat $Func_name.txt | tree2dotx > $Func_name.dot
dot -Tgif $Func_name.dot -o $Func_name.gif
echo "functions gif finished!"
